### ISSUE TITLE
Add node_modules to search path when resolving modules.

### ISSUE THREAD

**Issue by grassator** [grassator/qml-commonjs#1]
Needs to operate according to this alghorithm
http://nodejs.org/api/modules.html#modules_all_together

**Comment by toby20130333** [comment]
qml: Error: Invalid write to global property "hasOwnProperty"
I run this test and found error ,any problem?

**Comment by grassator** [comment]
After a quick look I would say that the most probably cause is that they changed the way `eval()` behaves in Qt 5.3 or Qt 5.4. I will be honest, I'm not sure when I will have time to investigate this.

**Comment by grassator** [comment]
@toby20130333 I've just pushed an update that should your error, but it also resulted in some changes to how the modules are resolved. Please see [README.md](https://github.com/grassator/qml-commonjs/) for details

**Comment by toby20130333** [comment]
@grassator Thank you I will have a try
